name       : perl-pod-parser
version    : 1.63
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/M/MA/MAREKR/Pod-Parser-1.63.tar.gz : dbe0b56129975b2f83a02841e8e0ed47be80f060686c66ea37e529d97aa70ccd
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Modules for parsing/translating POD format documents
description: |
    Basic perl modules for handling Plain Old Documentation (POD).
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
