name       : perl-pod-parser
version    : '1.66'
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/M/MA/MAREKR/Pod-Parser-1.66.tar.gz : 22928a7bffe61b452c05bbbb8f5216d4b9cf9fe2a849b776c25500d24d20df7c
homepage   : https://metacpan.org/pod/Pod::Parser
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Pod::Parser - base class for creating POD filters and translators
description: |
    Pod::Parser is a base class for creating POD filters and translators. It handles most of the effort involved with parsing the POD sections from an input stream, leaving subclasses free to be concerned only with performing the actual translation of text.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
