name       : perl-pod-parser
version    : '1.65'
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/M/MA/MAREKR/Pod-Parser-1.65.tar.gz : 3ba7bdec659416a51fe2a7e59f0883e9c6a3b21bc9d001042c1d6a32d401b28a
homepage   : https://metacpan.org/pod/Pod::Parser
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Pod::Parser - base class for creating POD filters and translators
description: |
    Pod::Parser is a base class for creating POD filters and translators. It handles most of the effort involved with parsing the POD sections from an input stream, leaving subclasses free to be concerned only with performing the actual translation of text.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
